/* Datos de checklists por juego.
 * Cada categoria puede ser de tipo "list" (items nombrados) o "grid" (coleccionables
 * numerados como Skulltulas Doradas o Piezas de Corazon, igual que el contador del propio juego).
 * Los IDs deben ser estables: si cambian, el progreso guardado de los usuarios se pierde.
 */
window.ZELDA_GAMES = [
  {
    id: "oot",
    name: "Ocarina of Time",
    subtitle: "The Legend of Zelda: Ocarina of Time (N64 / 3DS)",
    color: "#2d6a4f",
    categories: [
      {
        id: "stones",
        name: "Piedras Espirituales",
        icon: "💎",
        type: "list",
        items: [
          { id: "kokiri-emerald", name: "Esmeralda Kokiri" },
          { id: "goron-ruby", name: "Rubí Goron" },
          { id: "zora-sapphire", name: "Zafiro Zora" },
        ],
      },
      {
        id: "medallions",
        name: "Medallones de los Sabios",
        icon: "🔶",
        type: "list",
        items: [
          { id: "med-forest", name: "Medallón del Bosque" },
          { id: "med-fire", name: "Medallón del Fuego" },
          { id: "med-water", name: "Medallón del Agua" },
          { id: "med-shadow", name: "Medallón de las Sombras" },
          { id: "med-spirit", name: "Medallón del Espíritu" },
          { id: "med-light", name: "Medallón de la Luz" },
        ],
      },
      {
        id: "songs",
        name: "Canciones de Ocarina",
        icon: "🎵",
        type: "list",
        items: [
          { id: "song-zelda", name: "Canción de Zelda" },
          { id: "song-saria", name: "Canción de Saria" },
          { id: "song-epona", name: "Canción de Epona" },
          { id: "song-sun", name: "Canción del Sol" },
          { id: "song-time", name: "Canción del Tiempo" },
          { id: "song-storms", name: "Canción de la Tormenta" },
          { id: "song-minuet", name: "Minueto del Bosque" },
          { id: "song-bolero", name: "Bolero del Fuego" },
          { id: "song-serenade", name: "Serenata del Agua" },
          { id: "song-nocturne", name: "Nocturno de las Sombras" },
          { id: "song-requiem", name: "Réquiem del Espíritu" },
          { id: "song-prelude", name: "Preludio de la Luz" },
          { id: "song-scarecrow", name: "Canción del Espantapájaros" },
        ],
      },
      {
        id: "weapons",
        name: "Armas y Herramientas",
        icon: "⚔️",
        type: "list",
        items: [
          { id: "kokiri-sword", name: "Espada Kokiri" },
          { id: "master-sword", name: "Espada Maestra" },
          { id: "biggoron-sword", name: "Espada de Biggoron" },
          { id: "deku-shield", name: "Escudo Deku" },
          { id: "hylian-shield", name: "Escudo Hyliano" },
          { id: "mirror-shield", name: "Escudo Espejo" },
          { id: "deku-sticks", name: "Palos Deku" },
          { id: "deku-nuts", name: "Nueces Deku" },
          { id: "slingshot", name: "Tirachinas de las Hadas" },
          { id: "bombs", name: "Bombas / Bolsa de Bombas" },
          { id: "bombchus", name: "Bombchus" },
          { id: "fairy-bow", name: "Arco de las Hadas" },
          { id: "fire-arrows", name: "Flechas de Fuego" },
          { id: "ice-arrows", name: "Flechas de Hielo" },
          { id: "light-arrows", name: "Flechas de Luz" },
          { id: "boomerang", name: "Bumerán" },
          { id: "hookshot", name: "Gancho" },
          { id: "longshot", name: "Gancho Largo" },
          { id: "megaton-hammer", name: "Martillo Megatón" },
          { id: "lens-of-truth", name: "Lupa de la Verdad" },
          { id: "iron-boots", name: "Botas de Hierro" },
          { id: "hover-boots", name: "Botas Saltarinas" },
          { id: "ocarina", name: "Ocarina (de las Hadas / del Tiempo)" },
        ],
      },
      {
        id: "magic",
        name: "Magia y Trajes",
        icon: "✨",
        type: "list",
        items: [
          { id: "dins-fire", name: "Fuego de Din" },
          { id: "farores-wind", name: "Viento de Farore" },
          { id: "nayrus-love", name: "Amor de Nayru" },
          { id: "goron-tunic", name: "Traje Goron" },
          { id: "zora-tunic", name: "Traje Zora" },
        ],
      },
      {
        id: "bottles",
        name: "Botellas",
        icon: "🍾",
        type: "list",
        items: [
          { id: "bottle-1", name: "Botella #1" },
          { id: "bottle-2", name: "Botella #2" },
          { id: "bottle-3", name: "Botella #3" },
          { id: "bottle-4", name: "Botella #4 (Gran Hada de Poe)" },
        ],
      },
      {
        id: "masks",
        name: "Máscaras",
        icon: "🎭",
        type: "list",
        items: [
          { id: "mask-keaton", name: "Máscara de Keaton" },
          { id: "mask-skull", name: "Máscara Calavera" },
          { id: "mask-spooky", name: "Máscara Espeluznante" },
          { id: "mask-bunny", name: "Careta de Conejo" },
          { id: "mask-goron", name: "Máscara Goron" },
          { id: "mask-zora", name: "Máscara Zora" },
          { id: "mask-gerudo", name: "Máscara Gerudo" },
          { id: "mask-truth", name: "Máscara de la Verdad" },
        ],
      },
      {
        id: "trading",
        name: "Secuencia de Intercambio (Adulto)",
        icon: "🔄",
        type: "list",
        items: [
          { id: "trade-pocket-egg", name: "Huevo de Bolsillo" },
          { id: "trade-pocket-cucco", name: "Cucco de Bolsillo" },
          { id: "trade-cojiro", name: "Cojiro" },
          { id: "trade-odd-mushroom", name: "Seta Extraña" },
          { id: "trade-odd-potion", name: "Poción Extraña" },
          { id: "trade-saw", name: "Sierra del Cazador" },
          { id: "trade-broken-sword", name: "Espada Rota del Gigante" },
          { id: "trade-prescription", name: "Receta" },
          { id: "trade-frog", name: "Rana de Ojo" },
          { id: "trade-eyedrops", name: "Colirio del Mundo" },
          { id: "trade-claim-check", name: "Recibo (Claim Check)" },
        ],
      },
      {
        id: "upgrades",
        name: "Mejoras y Equipamiento",
        icon: "📈",
        type: "list",
        items: [
          { id: "up-bombbag-20", name: "Bolsa de Bombas (20)" },
          { id: "up-bombbag-30", name: "Bolsa de Bombas (30)" },
          { id: "up-bombbag-40", name: "Bolsa de Bombas (40)" },
          { id: "up-quiver-30", name: "Carcaj (30 flechas)" },
          { id: "up-quiver-40", name: "Carcaj (40 flechas)" },
          { id: "up-quiver-50", name: "Carcaj (50 flechas)" },
          { id: "up-stick-20", name: "Bolsillo Palos Deku (20)" },
          { id: "up-stick-30", name: "Bolsillo Palos Deku (30)" },
          { id: "up-nut-30", name: "Bolsillo Nueces Deku (30)" },
          { id: "up-nut-40", name: "Bolsillo Nueces Deku (40)" },
          { id: "up-wallet-adult", name: "Billetera de Adulto (200)" },
          { id: "up-wallet-giant", name: "Billetera Gigante (500)" },
          { id: "up-scale-silver", name: "Escama de Plata" },
          { id: "up-scale-gold", name: "Escama Dorada" },
          { id: "up-gauntlets-silver", name: "Guantes de Plata" },
          { id: "up-gauntlets-gold", name: "Guantes Dorados" },
          { id: "up-stone-agony", name: "Piedra de la Agonía" },
          { id: "up-magic", name: "Ampliación de Magia" },
          { id: "up-magic-double", name: "Doble Magia" },
        ],
      },
      {
        id: "bosses",
        name: "Jefes y Contenedores de Corazón",
        icon: "❤️",
        type: "list",
        items: [
          { id: "boss-gohma", name: "Gohma (Gran Árbol Deku)" },
          { id: "boss-dodongo", name: "Rey Dodongo (Caverna Dodongo)" },
          { id: "boss-barinade", name: "Barinade (Vientre de Jabu-Jabu)" },
          { id: "boss-phantom-ganon", name: "Phantom Ganon (Templo del Bosque)" },
          { id: "boss-volvagia", name: "Volvagia (Templo del Fuego)" },
          { id: "boss-morpha", name: "Morpha (Templo del Agua)" },
          { id: "boss-bongo-bongo", name: "Bongo Bongo (Templo de las Sombras)" },
          { id: "boss-twinrova", name: "Twinrova (Templo del Espíritu)" },
          { id: "boss-ganon", name: "Ganon (batalla final)" },
        ],
      },
      {
        id: "dungeons",
        name: "Mazmorras Completadas",
        icon: "🏰",
        type: "list",
        items: [
          { id: "dun-deku-tree", name: "Gran Árbol Deku" },
          { id: "dun-dodongo", name: "Caverna Dodongo" },
          { id: "dun-jabu", name: "Vientre de Jabu-Jabu" },
          { id: "dun-forest", name: "Templo del Bosque" },
          { id: "dun-fire", name: "Templo del Fuego" },
          { id: "dun-water", name: "Templo del Agua" },
          { id: "dun-well", name: "Pozo del Fondo (Bottom of the Well)" },
          { id: "dun-shadow", name: "Templo de las Sombras" },
          { id: "dun-spirit", name: "Templo del Espíritu" },
          { id: "dun-ice", name: "Caverna de Hielo" },
          { id: "dun-gtg", name: "Terreno de Entrenamiento Gerudo" },
          { id: "dun-ganons-castle", name: "Castillo de Ganon" },
        ],
      },
      {
        id: "heart-pieces",
        name: "Piezas de Corazón",
        icon: "💗",
        type: "grid",
        count: 36,
        note: "36 piezas = 9 contenedores extra de corazón.",
      },
      {
        id: "skulltulas-dungeons",
        name: "Skulltulas Doradas — Mazmorras",
        icon: "🕷️",
        type: "grid",
        count: 50,
        note: "5 por cada una de las 10 mazmorras con Skulltulas.",
      },
      {
        id: "skulltulas-overworld",
        name: "Skulltulas Doradas — Mundo",
        icon: "🕸️",
        type: "grid",
        count: 50,
        note: "Repartidas por Hyrule. Muchas solo aparecen de noche.",
      },
    ],
  },
  {
    id: "mm",
    name: "Majora's Mask",
    subtitle: "The Legend of Zelda: Majora's Mask (N64 / 3DS)",
    color: "#5a3d8a",
    categories: [
      {
        id: "mm-transformation-masks",
        name: "Máscaras de Transformación",
        icon: "🎭",
        type: "list",
        items: [
          { id: "mm-mask-deku", name: "Máscara Deku" },
          { id: "mm-mask-goron", name: "Máscara Goron" },
          { id: "mm-mask-zora", name: "Máscara Zora" },
          { id: "mm-mask-fierce-deity", name: "Máscara de la Deidad Feroz" },
        ],
      },
      {
        id: "mm-masks",
        name: "Otras Máscaras",
        icon: "🎪",
        type: "list",
        items: [
          { id: "mm-mask-moon", name: "Máscara de la Luna" },
          { id: "mm-mask-all-night", name: "Máscara del Trasnoche" },
          { id: "mm-mask-bunny-hood", name: "Careta de Conejo" },
          { id: "mm-mask-keaton", name: "Máscara de Keaton" },
          { id: "mm-mask-garo", name: "Máscara Garo" },
          { id: "mm-mask-romani", name: "Máscara de Romani" },
          { id: "mm-mask-circus-leader", name: "Máscara del Líder del Circo" },
          { id: "mm-mask-postman", name: "Gorro de Cartero" },
          { id: "mm-mask-couple", name: "Máscara de los Novios" },
          { id: "mm-mask-great-fairy", name: "Máscara de la Gran Hada" },
          { id: "mm-mask-gibdo", name: "Máscara Gibdo" },
          { id: "mm-mask-don-gero", name: "Máscara de Don Gero" },
          { id: "mm-mask-kamaro", name: "Máscara de Kamaro" },
          { id: "mm-mask-captains-hat", name: "Casco del Capitán" },
          { id: "mm-mask-giants", name: "Máscara de los Gigantes" },
          { id: "mm-mask-blast", name: "Máscara Explosiva" },
          { id: "mm-mask-stone", name: "Máscara de Piedra" },
          { id: "mm-mask-scents", name: "Máscara de Aromas" },
          { id: "mm-mask-truth", name: "Máscara de la Verdad" },
        ],
      },
      {
        id: "mm-songs",
        name: "Canciones",
        icon: "🎵",
        type: "list",
        items: [
          { id: "mm-song-oath", name: "Canción del Juramento" },
          { id: "mm-song-healing", name: "Canción de Curación" },
          { id: "mm-song-time", name: "Canción del Tiempo" },
          { id: "mm-song-sonata", name: "Sonata de la Tempestad" },
          { id: "mm-song-lullaby", name: "Canción de Cuna de la Nueva Onda" },
          { id: "mm-song-elegy", name: "Elegía de la Emptiness" },
          { id: "mm-song-oath-goron", name: "Canción del Juramento a un Amigo (obtención)" },
          { id: "mm-song-sarias", name: "Canción de Saria" },
          { id: "mm-song-suns", name: "Canción del Sol" },
          { id: "mm-song-storms", name: "Canción de la Tormenta" },
          { id: "mm-song-epona", name: "Canción de Epona" },
          { id: "mm-song-goron-lullaby", name: "Canción de Cuna Goron" },
        ],
      },
      {
        id: "mm-dungeons",
        name: "Mazmorras y Gigantes",
        icon: "🏰",
        type: "list",
        items: [
          { id: "mm-woodfall", name: "Templo del Pantano (Woodfall)" },
          { id: "mm-snowhead", name: "Templo de las Nieves (Snowhead)" },
          { id: "mm-great-bay", name: "Templo del Gran Mar (Great Bay)" },
          { id: "mm-stone-tower", name: "Templo de la Torre de Piedra (Stone Tower)" },
        ],
      },
      {
        id: "mm-heart-pieces",
        name: "Piezas de Corazón",
        icon: "💗",
        type: "grid",
        count: 44,
        note: "44 piezas = 11 contenedores extra de corazón.",
      },
      {
        id: "mm-stray-fairies",
        name: "Hadas Perdidas",
        icon: "🧚",
        type: "grid",
        count: 60,
        note: "15 por cada una de las 4 mazmorras.",
      },
    ],
  },
];
