/* Datos de checklists por juego.
 * Cada categoria puede ser de tipo:
 *   - "list": items nombrados sueltos.
 *   - "grid": coleccionables numerados sin ubicación (contador simple).
 *   - "grouped-list": coleccionables numerados pero agrupados por zona/mazmorra,
 *     para saber DONDE está cada uno (usado en Piezas de Corazón y Skulltulas).
 * Los IDs deben ser estables: si cambian, el progreso guardado de los usuarios se pierde.
 */
window.ZELDA_GAMES = [
  {
    id: "oot",
    name: "Ocarina of Time",
    subtitle: "The Legend of Zelda: Ocarina of Time (N64 / 3DS)",
    color: "#2d6a4f",
    categories: [
      {
        id: "stones",
        name: "Piedras Espirituales",
        icon: "💎",
        type: "list",
        items: [
          { id: "kokiri-emerald", name: "Esmeralda Kokiri" },
          { id: "goron-ruby", name: "Rubí Goron" },
          { id: "zora-sapphire", name: "Zafiro Zora" },
        ],
      },
      {
        id: "medallions",
        name: "Medallones de los Sabios",
        icon: "🔶",
        type: "list",
        items: [
          { id: "med-forest", name: "Medallón del Bosque" },
          { id: "med-fire", name: "Medallón del Fuego" },
          { id: "med-water", name: "Medallón del Agua" },
          { id: "med-shadow", name: "Medallón de las Sombras" },
          { id: "med-spirit", name: "Medallón del Espíritu" },
          { id: "med-light", name: "Medallón de la Luz" },
        ],
      },
      {
        id: "songs",
        name: "Canciones de Ocarina",
        icon: "🎵",
        type: "list",
        items: [
          { id: "song-zelda", name: "Canción de Zelda" },
          { id: "song-saria", name: "Canción de Saria" },
          { id: "song-epona", name: "Canción de Epona" },
          { id: "song-sun", name: "Canción del Sol" },
          { id: "song-time", name: "Canción del Tiempo" },
          { id: "song-storms", name: "Canción de la Tormenta" },
          { id: "song-minuet", name: "Minueto del Bosque" },
          { id: "song-bolero", name: "Bolero del Fuego" },
          { id: "song-serenade", name: "Serenata del Agua" },
          { id: "song-nocturne", name: "Nocturno de las Sombras" },
          { id: "song-requiem", name: "Réquiem del Espíritu" },
          { id: "song-prelude", name: "Preludio de la Luz" },
          { id: "song-scarecrow", name: "Canción del Espantapájaros" },
        ],
      },
      {
        id: "weapons",
        name: "Armas y Herramientas",
        icon: "⚔️",
        type: "list",
        items: [
          { id: "kokiri-sword", name: "Espada Kokiri" },
          { id: "master-sword", name: "Espada Maestra" },
          { id: "biggoron-sword", name: "Espada de Biggoron" },
          { id: "deku-shield", name: "Escudo Deku" },
          { id: "hylian-shield", name: "Escudo Hyliano" },
          { id: "mirror-shield", name: "Escudo Espejo" },
          { id: "deku-sticks", name: "Palos Deku" },
          { id: "deku-nuts", name: "Nueces Deku" },
          { id: "slingshot", name: "Tirachinas de las Hadas" },
          { id: "bombs", name: "Bombas / Bolsa de Bombas" },
          { id: "bombchus", name: "Bombchus" },
          { id: "fairy-bow", name: "Arco de las Hadas" },
          { id: "fire-arrows", name: "Flechas de Fuego" },
          { id: "ice-arrows", name: "Flechas de Hielo" },
          { id: "light-arrows", name: "Flechas de Luz" },
          { id: "boomerang", name: "Bumerán" },
          { id: "hookshot", name: "Gancho" },
          { id: "longshot", name: "Gancho Largo" },
          { id: "megaton-hammer", name: "Martillo Megatón" },
          { id: "lens-of-truth", name: "Lupa de la Verdad" },
          { id: "iron-boots", name: "Botas de Hierro" },
          { id: "hover-boots", name: "Botas Saltarinas" },
          { id: "ocarina", name: "Ocarina (de las Hadas / del Tiempo)" },
        ],
      },
      {
        id: "magic",
        name: "Magia y Trajes",
        icon: "✨",
        type: "list",
        items: [
          { id: "dins-fire", name: "Fuego de Din" },
          { id: "farores-wind", name: "Viento de Farore" },
          { id: "nayrus-love", name: "Amor de Nayru" },
          { id: "goron-tunic", name: "Traje Goron" },
          { id: "zora-tunic", name: "Traje Zora" },
        ],
      },
      {
        id: "bottles",
        name: "Botellas",
        icon: "🍾",
        type: "list",
        items: [
          { id: "bottle-1", name: "Botella #1" },
          { id: "bottle-2", name: "Botella #2" },
          { id: "bottle-3", name: "Botella #3" },
          { id: "bottle-4", name: "Botella #4 (Gran Hada de Poe)" },
        ],
      },
      {
        id: "masks",
        name: "Máscaras",
        icon: "🎭",
        type: "list",
        items: [
          { id: "mask-keaton", name: "Máscara de Keaton" },
          { id: "mask-skull", name: "Máscara Calavera" },
          { id: "mask-spooky", name: "Máscara Espeluznante" },
          { id: "mask-bunny", name: "Careta de Conejo" },
          { id: "mask-goron", name: "Máscara Goron" },
          { id: "mask-zora", name: "Máscara Zora" },
          { id: "mask-gerudo", name: "Máscara Gerudo" },
          { id: "mask-truth", name: "Máscara de la Verdad" },
        ],
      },
      {
        id: "trading",
        name: "Secuencia de Intercambio (Adulto)",
        icon: "🔄",
        type: "list",
        items: [
          { id: "trade-pocket-egg", name: "Huevo de Bolsillo" },
          { id: "trade-pocket-cucco", name: "Cucco de Bolsillo" },
          { id: "trade-cojiro", name: "Cojiro" },
          { id: "trade-odd-mushroom", name: "Seta Extraña" },
          { id: "trade-odd-potion", name: "Poción Extraña" },
          { id: "trade-saw", name: "Sierra del Cazador" },
          { id: "trade-broken-sword", name: "Espada Rota del Gigante" },
          { id: "trade-prescription", name: "Receta" },
          { id: "trade-frog", name: "Rana de Ojo" },
          { id: "trade-eyedrops", name: "Colirio del Mundo" },
          { id: "trade-claim-check", name: "Recibo (Claim Check)" },
        ],
      },
      {
        id: "upgrades",
        name: "Mejoras y Equipamiento",
        icon: "📈",
        type: "list",
        items: [
          { id: "up-bombbag-20", name: "Bolsa de Bombas (20)" },
          { id: "up-bombbag-30", name: "Bolsa de Bombas (30)" },
          { id: "up-bombbag-40", name: "Bolsa de Bombas (40)" },
          { id: "up-quiver-30", name: "Carcaj (30 flechas)" },
          { id: "up-quiver-40", name: "Carcaj (40 flechas)" },
          { id: "up-quiver-50", name: "Carcaj (50 flechas)" },
          { id: "up-stick-20", name: "Bolsillo Palos Deku (20)" },
          { id: "up-stick-30", name: "Bolsillo Palos Deku (30)" },
          { id: "up-nut-30", name: "Bolsillo Nueces Deku (30)" },
          { id: "up-nut-40", name: "Bolsillo Nueces Deku (40)" },
          { id: "up-wallet-adult", name: "Billetera de Adulto (200)" },
          { id: "up-wallet-giant", name: "Billetera Gigante (500)" },
          { id: "up-scale-silver", name: "Escama de Plata" },
          { id: "up-scale-gold", name: "Escama Dorada" },
          { id: "up-gauntlets-silver", name: "Guantes de Plata" },
          { id: "up-gauntlets-gold", name: "Guantes Dorados" },
          { id: "up-stone-agony", name: "Piedra de la Agonía" },
          { id: "up-magic", name: "Ampliación de Magia" },
          { id: "up-magic-double", name: "Doble Magia" },
        ],
      },
      {
        id: "bosses",
        name: "Jefes y Contenedores de Corazón",
        icon: "❤️",
        type: "list",
        items: [
          { id: "boss-gohma", name: "Gohma (Gran Árbol Deku)" },
          { id: "boss-dodongo", name: "Rey Dodongo (Caverna Dodongo)" },
          { id: "boss-barinade", name: "Barinade (Vientre de Jabu-Jabu)" },
          { id: "boss-phantom-ganon", name: "Phantom Ganon (Templo del Bosque)" },
          { id: "boss-volvagia", name: "Volvagia (Templo del Fuego)" },
          { id: "boss-morpha", name: "Morpha (Templo del Agua)" },
          { id: "boss-bongo-bongo", name: "Bongo Bongo (Templo de las Sombras)" },
          { id: "boss-twinrova", name: "Twinrova (Templo del Espíritu)" },
          { id: "boss-ganon", name: "Ganon (batalla final)" },
        ],
      },
      {
        id: "dungeons",
        name: "Mazmorras Completadas",
        icon: "🏰",
        type: "list",
        items: [
          { id: "dun-deku-tree", name: "Gran Árbol Deku" },
          { id: "dun-dodongo", name: "Caverna Dodongo" },
          { id: "dun-jabu", name: "Vientre de Jabu-Jabu" },
          { id: "dun-forest", name: "Templo del Bosque" },
          { id: "dun-fire", name: "Templo del Fuego" },
          { id: "dun-water", name: "Templo del Agua" },
          { id: "dun-well", name: "Pozo del Fondo (Bottom of the Well)" },
          { id: "dun-shadow", name: "Templo de las Sombras" },
          { id: "dun-spirit", name: "Templo del Espíritu" },
          { id: "dun-ice", name: "Caverna de Hielo" },
          { id: "dun-gtg", name: "Terreno de Entrenamiento Gerudo" },
          { id: "dun-ganons-castle", name: "Castillo de Ganon" },
        ],
      },
      {
        id: "heart-pieces",
        name: "Piezas de Corazón",
        icon: "💗",
        type: "grouped-list",
        note: "36 piezas = 9 contenedores extra de corazón.",
        groups: [
        {
          id: "hp-deku-tree",
          name: "Gran Árbol Deku",
          items: [
          { id: "hp-deku-tree-1", name: "#1" },
          ],
        },
        {
          id: "hp-dodongo",
          name: "Caverna Dodongo",
          items: [
          { id: "hp-dodongo-1", name: "#1" },
          ],
        },
        {
          id: "hp-forest-temple",
          name: "Templo del Bosque",
          items: [
          { id: "hp-forest-temple-1", name: "#1" },
          ],
        },
        {
          id: "hp-fire-temple",
          name: "Templo del Fuego",
          items: [
          { id: "hp-fire-temple-1", name: "#1" },
          ],
        },
        {
          id: "hp-water-temple",
          name: "Templo del Agua",
          items: [
          { id: "hp-water-temple-1", name: "#1" },
          ],
        },
        {
          id: "hp-bottom-well",
          name: "Pozo del Fondo",
          items: [
          { id: "hp-bottom-well-1", name: "#1" },
          ],
        },
        {
          id: "hp-ice-cavern",
          name: "Caverna de Hielo",
          items: [
          { id: "hp-ice-cavern-1", name: "#1" },
          ],
        },
        {
          id: "hp-gtg",
          name: "Terreno de Entrenamiento Gerudo",
          items: [
          { id: "hp-gtg-1", name: "#1" },
          ],
        },
        {
          id: "hp-ganons-castle",
          name: "Castillo de Ganon (ruinas)",
          items: [
          { id: "hp-ganons-castle-1", name: "#1" },
          ],
        },
        {
          id: "hp-lost-woods",
          name: "Bosque Perdido / Prado Sagrado",
          items: [
          { id: "hp-lost-woods-1", name: "#1" },
          { id: "hp-lost-woods-2", name: "#2" },
          ],
        },
        {
          id: "hp-hyrule-field",
          name: "Pradera de Hyrule",
          items: [
          { id: "hp-hyrule-field-1", name: "#1" },
          { id: "hp-hyrule-field-2", name: "#2" },
          ],
        },
        {
          id: "hp-market",
          name: "Mercado / Ciudadela de Hyrule",
          items: [
          { id: "hp-market-1", name: "#1" },
          { id: "hp-market-2", name: "#2" },
          ],
        },
        {
          id: "hp-lon-lon",
          name: "Rancho Lon Lon",
          items: [
          { id: "hp-lon-lon-1", name: "#1" },
          { id: "hp-lon-lon-2", name: "#2" },
          ],
        },
        {
          id: "hp-kakariko",
          name: "Pueblo Kakariko",
          items: [
          { id: "hp-kakariko-1", name: "#1" },
          { id: "hp-kakariko-2", name: "#2" },
          ],
        },
        {
          id: "hp-graveyard",
          name: "Cementerio",
          items: [
          { id: "hp-graveyard-1", name: "#1" },
          { id: "hp-graveyard-2", name: "#2" },
          { id: "hp-graveyard-3", name: "#3" },
          ],
        },
        {
          id: "hp-dmt",
          name: "Sendero de la Montaña de la Muerte",
          items: [
          { id: "hp-dmt-1", name: "#1" },
          { id: "hp-dmt-2", name: "#2" },
          ],
        },
        {
          id: "hp-goron-city",
          name: "Ciudad Goron",
          items: [
          { id: "hp-goron-city-1", name: "#1" },
          ],
        },
        {
          id: "hp-dmc",
          name: "Cráter de la Montaña de la Muerte",
          items: [
          { id: "hp-dmc-1", name: "#1" },
          { id: "hp-dmc-2", name: "#2" },
          ],
        },
        {
          id: "hp-zora-river",
          name: "Río Zora",
          items: [
          { id: "hp-zora-river-1", name: "#1" },
          ],
        },
        {
          id: "hp-zora-domain",
          name: "Reino Zora",
          items: [
          { id: "hp-zora-domain-1", name: "#1" },
          ],
        },
        {
          id: "hp-lake-hylia",
          name: "Lago Hylia",
          items: [
          { id: "hp-lake-hylia-1", name: "#1" },
          { id: "hp-lake-hylia-2", name: "#2" },
          ],
        },
        {
          id: "hp-gerudo-valley",
          name: "Valle Gerudo",
          items: [
          { id: "hp-gerudo-valley-1", name: "#1" },
          { id: "hp-gerudo-valley-2", name: "#2" },
          ],
        },
        {
          id: "hp-gerudo-fortress",
          name: "Fortaleza Gerudo",
          items: [
          { id: "hp-gerudo-fortress-1", name: "#1" },
          { id: "hp-gerudo-fortress-2", name: "#2" },
          ],
        },
        {
          id: "hp-desert-colossus",
          name: "Coloso del Desierto",
          items: [
          { id: "hp-desert-colossus-1", name: "#1" },
          ],
        },
        ],
      },
      {
        id: "skulltulas-dungeons",
        name: "Skulltulas Doradas — Mazmorras",
        icon: "🕷️",
        type: "grouped-list",
        note: "5 por cada una de las 10 mazmorras con Skulltulas.",
        groups: [
        {
          id: "sk-deku-tree",
          name: "Gran Árbol Deku",
          items: [
          { id: "sk-deku-tree-1", name: "#1" },
          { id: "sk-deku-tree-2", name: "#2" },
          { id: "sk-deku-tree-3", name: "#3" },
          { id: "sk-deku-tree-4", name: "#4" },
          { id: "sk-deku-tree-5", name: "#5" },
          ],
        },
        {
          id: "sk-dodongo",
          name: "Caverna Dodongo",
          items: [
          { id: "sk-dodongo-1", name: "#1" },
          { id: "sk-dodongo-2", name: "#2" },
          { id: "sk-dodongo-3", name: "#3" },
          { id: "sk-dodongo-4", name: "#4" },
          { id: "sk-dodongo-5", name: "#5" },
          ],
        },
        {
          id: "sk-jabu",
          name: "Vientre de Jabu-Jabu",
          items: [
          { id: "sk-jabu-1", name: "#1" },
          { id: "sk-jabu-2", name: "#2" },
          { id: "sk-jabu-3", name: "#3" },
          { id: "sk-jabu-4", name: "#4" },
          { id: "sk-jabu-5", name: "#5" },
          ],
        },
        {
          id: "sk-forest-temple",
          name: "Templo del Bosque",
          items: [
          { id: "sk-forest-temple-1", name: "#1" },
          { id: "sk-forest-temple-2", name: "#2" },
          { id: "sk-forest-temple-3", name: "#3" },
          { id: "sk-forest-temple-4", name: "#4" },
          { id: "sk-forest-temple-5", name: "#5" },
          ],
        },
        {
          id: "sk-fire-temple",
          name: "Templo del Fuego",
          items: [
          { id: "sk-fire-temple-1", name: "#1" },
          { id: "sk-fire-temple-2", name: "#2" },
          { id: "sk-fire-temple-3", name: "#3" },
          { id: "sk-fire-temple-4", name: "#4" },
          { id: "sk-fire-temple-5", name: "#5" },
          ],
        },
        {
          id: "sk-water-temple",
          name: "Templo del Agua",
          items: [
          { id: "sk-water-temple-1", name: "#1" },
          { id: "sk-water-temple-2", name: "#2" },
          { id: "sk-water-temple-3", name: "#3" },
          { id: "sk-water-temple-4", name: "#4" },
          { id: "sk-water-temple-5", name: "#5" },
          ],
        },
        {
          id: "sk-bottom-well",
          name: "Pozo del Fondo",
          items: [
          { id: "sk-bottom-well-1", name: "#1" },
          { id: "sk-bottom-well-2", name: "#2" },
          { id: "sk-bottom-well-3", name: "#3" },
          { id: "sk-bottom-well-4", name: "#4" },
          { id: "sk-bottom-well-5", name: "#5" },
          ],
        },
        {
          id: "sk-shadow-temple",
          name: "Templo de las Sombras",
          items: [
          { id: "sk-shadow-temple-1", name: "#1" },
          { id: "sk-shadow-temple-2", name: "#2" },
          { id: "sk-shadow-temple-3", name: "#3" },
          { id: "sk-shadow-temple-4", name: "#4" },
          { id: "sk-shadow-temple-5", name: "#5" },
          ],
        },
        {
          id: "sk-spirit-temple",
          name: "Templo del Espíritu",
          items: [
          { id: "sk-spirit-temple-1", name: "#1" },
          { id: "sk-spirit-temple-2", name: "#2" },
          { id: "sk-spirit-temple-3", name: "#3" },
          { id: "sk-spirit-temple-4", name: "#4" },
          { id: "sk-spirit-temple-5", name: "#5" },
          ],
        },
        {
          id: "sk-ice-cavern",
          name: "Caverna de Hielo",
          items: [
          { id: "sk-ice-cavern-1", name: "#1" },
          { id: "sk-ice-cavern-2", name: "#2" },
          { id: "sk-ice-cavern-3", name: "#3" },
          { id: "sk-ice-cavern-4", name: "#4" },
          { id: "sk-ice-cavern-5", name: "#5" },
          ],
        },
        ],
      },
      {
        id: "skulltulas-overworld",
        name: "Skulltulas Doradas — Mundo",
        icon: "🕸️",
        type: "grouped-list",
        note: "Repartidas por Hyrule. Muchas solo aparecen de noche.",
        groups: [
        {
          id: "sk-kokiri-forest",
          name: "Bosque Kokiri",
          items: [
          { id: "sk-kokiri-forest-1", name: "#1" },
          { id: "sk-kokiri-forest-2", name: "#2" },
          { id: "sk-kokiri-forest-3", name: "#3" },
          ],
        },
        {
          id: "sk-lost-woods",
          name: "Bosque Perdido",
          items: [
          { id: "sk-lost-woods-1", name: "#1" },
          { id: "sk-lost-woods-2", name: "#2" },
          { id: "sk-lost-woods-3", name: "#3" },
          ],
        },
        {
          id: "sk-hyrule-field",
          name: "Pradera de Hyrule",
          items: [
          { id: "sk-hyrule-field-1", name: "#1" },
          { id: "sk-hyrule-field-2", name: "#2" },
          { id: "sk-hyrule-field-3", name: "#3" },
          { id: "sk-hyrule-field-4", name: "#4" },
          { id: "sk-hyrule-field-5", name: "#5" },
          ],
        },
        {
          id: "sk-market",
          name: "Mercado / Ciudadela de Hyrule",
          items: [
          { id: "sk-market-1", name: "#1" },
          { id: "sk-market-2", name: "#2" },
          { id: "sk-market-3", name: "#3" },
          ],
        },
        {
          id: "sk-lon-lon",
          name: "Rancho Lon Lon",
          items: [
          { id: "sk-lon-lon-1", name: "#1" },
          { id: "sk-lon-lon-2", name: "#2" },
          { id: "sk-lon-lon-3", name: "#3" },
          ],
        },
        {
          id: "sk-kakariko",
          name: "Pueblo Kakariko",
          items: [
          { id: "sk-kakariko-1", name: "#1" },
          { id: "sk-kakariko-2", name: "#2" },
          { id: "sk-kakariko-3", name: "#3" },
          { id: "sk-kakariko-4", name: "#4" },
          { id: "sk-kakariko-5", name: "#5" },
          ],
        },
        {
          id: "sk-graveyard",
          name: "Cementerio",
          items: [
          { id: "sk-graveyard-1", name: "#1" },
          { id: "sk-graveyard-2", name: "#2" },
          { id: "sk-graveyard-3", name: "#3" },
          ],
        },
        {
          id: "sk-dmt",
          name: "Sendero de la Montaña de la Muerte",
          items: [
          { id: "sk-dmt-1", name: "#1" },
          { id: "sk-dmt-2", name: "#2" },
          { id: "sk-dmt-3", name: "#3" },
          ],
        },
        {
          id: "sk-goron-city",
          name: "Ciudad Goron",
          items: [
          { id: "sk-goron-city-1", name: "#1" },
          ],
        },
        {
          id: "sk-dmc",
          name: "Cráter de la Montaña de la Muerte",
          items: [
          { id: "sk-dmc-1", name: "#1" },
          { id: "sk-dmc-2", name: "#2" },
          ],
        },
        {
          id: "sk-zora-river",
          name: "Río Zora",
          items: [
          { id: "sk-zora-river-1", name: "#1" },
          { id: "sk-zora-river-2", name: "#2" },
          ],
        },
        {
          id: "sk-zora-domain",
          name: "Reino Zora",
          items: [
          { id: "sk-zora-domain-1", name: "#1" },
          ],
        },
        {
          id: "sk-zora-fountain",
          name: "Fuente Zora",
          items: [
          { id: "sk-zora-fountain-1", name: "#1" },
          { id: "sk-zora-fountain-2", name: "#2" },
          ],
        },
        {
          id: "sk-lake-hylia",
          name: "Lago Hylia",
          items: [
          { id: "sk-lake-hylia-1", name: "#1" },
          { id: "sk-lake-hylia-2", name: "#2" },
          { id: "sk-lake-hylia-3", name: "#3" },
          { id: "sk-lake-hylia-4", name: "#4" },
          { id: "sk-lake-hylia-5", name: "#5" },
          ],
        },
        {
          id: "sk-gerudo-valley",
          name: "Valle Gerudo",
          items: [
          { id: "sk-gerudo-valley-1", name: "#1" },
          { id: "sk-gerudo-valley-2", name: "#2" },
          { id: "sk-gerudo-valley-3", name: "#3" },
          { id: "sk-gerudo-valley-4", name: "#4" },
          ],
        },
        {
          id: "sk-gerudo-fortress",
          name: "Fortaleza Gerudo",
          items: [
          { id: "sk-gerudo-fortress-1", name: "#1" },
          { id: "sk-gerudo-fortress-2", name: "#2" },
          ],
        },
        {
          id: "sk-wasteland",
          name: "Desierto de los Espectros",
          items: [
          { id: "sk-wasteland-1", name: "#1" },
          ],
        },
        {
          id: "sk-desert-colossus",
          name: "Coloso del Desierto",
          items: [
          { id: "sk-desert-colossus-1", name: "#1" },
          { id: "sk-desert-colossus-2", name: "#2" },
          ],
        },
        ],
      },
    ],
  },
  {
    id: "mm",
    name: "Majora's Mask",
    subtitle: "The Legend of Zelda: Majora's Mask (N64 / 3DS)",
    color: "#5a3d8a",
    categories: [
      {
        id: "mm-transformation-masks",
        name: "Máscaras de Transformación",
        icon: "🎭",
        type: "list",
        items: [
          { id: "mm-mask-deku", name: "Máscara Deku" },
          { id: "mm-mask-goron", name: "Máscara Goron" },
          { id: "mm-mask-zora", name: "Máscara Zora" },
          { id: "mm-mask-fierce-deity", name: "Máscara de la Deidad Feroz" },
        ],
      },
      {
        id: "mm-masks",
        name: "Otras Máscaras",
        icon: "🎪",
        type: "list",
        items: [
          { id: "mm-mask-moon", name: "Máscara de la Luna" },
          { id: "mm-mask-all-night", name: "Máscara del Trasnoche" },
          { id: "mm-mask-bunny-hood", name: "Careta de Conejo" },
          { id: "mm-mask-keaton", name: "Máscara de Keaton" },
          { id: "mm-mask-garo", name: "Máscara Garo" },
          { id: "mm-mask-romani", name: "Máscara de Romani" },
          { id: "mm-mask-circus-leader", name: "Máscara del Líder del Circo" },
          { id: "mm-mask-postman", name: "Gorro de Cartero" },
          { id: "mm-mask-couple", name: "Máscara de los Novios" },
          { id: "mm-mask-great-fairy", name: "Máscara de la Gran Hada" },
          { id: "mm-mask-gibdo", name: "Máscara Gibdo" },
          { id: "mm-mask-don-gero", name: "Máscara de Don Gero" },
          { id: "mm-mask-kamaro", name: "Máscara de Kamaro" },
          { id: "mm-mask-captains-hat", name: "Casco del Capitán" },
          { id: "mm-mask-giants", name: "Máscara de los Gigantes" },
          { id: "mm-mask-blast", name: "Máscara Explosiva" },
          { id: "mm-mask-stone", name: "Máscara de Piedra" },
          { id: "mm-mask-scents", name: "Máscara de Aromas" },
          { id: "mm-mask-truth", name: "Máscara de la Verdad" },
        ],
      },
      {
        id: "mm-songs",
        name: "Canciones",
        icon: "🎵",
        type: "list",
        items: [
          { id: "mm-song-oath", name: "Canción del Juramento" },
          { id: "mm-song-healing", name: "Canción de Curación" },
          { id: "mm-song-time", name: "Canción del Tiempo" },
          { id: "mm-song-sonata", name: "Sonata de la Tempestad" },
          { id: "mm-song-lullaby", name: "Canción de Cuna de la Nueva Onda" },
          { id: "mm-song-elegy", name: "Elegía de la Emptiness" },
          { id: "mm-song-oath-goron", name: "Canción del Juramento a un Amigo (obtención)" },
          { id: "mm-song-sarias", name: "Canción de Saria" },
          { id: "mm-song-suns", name: "Canción del Sol" },
          { id: "mm-song-storms", name: "Canción de la Tormenta" },
          { id: "mm-song-epona", name: "Canción de Epona" },
          { id: "mm-song-goron-lullaby", name: "Canción de Cuna Goron" },
        ],
      },
      {
        id: "mm-dungeons",
        name: "Mazmorras y Gigantes",
        icon: "🏰",
        type: "list",
        items: [
          { id: "mm-woodfall", name: "Templo del Pantano (Woodfall)" },
          { id: "mm-snowhead", name: "Templo de las Nieves (Snowhead)" },
          { id: "mm-great-bay", name: "Templo del Gran Mar (Great Bay)" },
          { id: "mm-stone-tower", name: "Templo de la Torre de Piedra (Stone Tower)" },
        ],
      },
      {
        id: "mm-heart-pieces",
        name: "Piezas de Corazón",
        icon: "💗",
        type: "grouped-list",
        note: "44 piezas = 11 contenedores extra de corazón.",
        groups: [
        {
          id: "mm-hp-clock-town",
          name: "Ciudad Reloj",
          items: [
          { id: "mm-hp-clock-town-1", name: "#1" },
          { id: "mm-hp-clock-town-2", name: "#2" },
          { id: "mm-hp-clock-town-3", name: "#3" },
          { id: "mm-hp-clock-town-4", name: "#4" },
          { id: "mm-hp-clock-town-5", name: "#5" },
          { id: "mm-hp-clock-town-6", name: "#6" },
          { id: "mm-hp-clock-town-7", name: "#7" },
          { id: "mm-hp-clock-town-8", name: "#8" },
          ],
        },
        {
          id: "mm-hp-termina-field",
          name: "Campo Termina",
          items: [
          { id: "mm-hp-termina-field-1", name: "#1" },
          { id: "mm-hp-termina-field-2", name: "#2" },
          { id: "mm-hp-termina-field-3", name: "#3" },
          { id: "mm-hp-termina-field-4", name: "#4" },
          { id: "mm-hp-termina-field-5", name: "#5" },
          { id: "mm-hp-termina-field-6", name: "#6" },
          ],
        },
        {
          id: "mm-hp-woodfall",
          name: "Pantano (Woodfall)",
          items: [
          { id: "mm-hp-woodfall-1", name: "#1" },
          { id: "mm-hp-woodfall-2", name: "#2" },
          { id: "mm-hp-woodfall-3", name: "#3" },
          { id: "mm-hp-woodfall-4", name: "#4" },
          { id: "mm-hp-woodfall-5", name: "#5" },
          { id: "mm-hp-woodfall-6", name: "#6" },
          ],
        },
        {
          id: "mm-hp-snowhead",
          name: "Montaña (Snowhead)",
          items: [
          { id: "mm-hp-snowhead-1", name: "#1" },
          { id: "mm-hp-snowhead-2", name: "#2" },
          { id: "mm-hp-snowhead-3", name: "#3" },
          { id: "mm-hp-snowhead-4", name: "#4" },
          { id: "mm-hp-snowhead-5", name: "#5" },
          { id: "mm-hp-snowhead-6", name: "#6" },
          { id: "mm-hp-snowhead-7", name: "#7" },
          { id: "mm-hp-snowhead-8", name: "#8" },
          ],
        },
        {
          id: "mm-hp-great-bay",
          name: "Bahía / Costa Zora (Great Bay)",
          items: [
          { id: "mm-hp-great-bay-1", name: "#1" },
          { id: "mm-hp-great-bay-2", name: "#2" },
          { id: "mm-hp-great-bay-3", name: "#3" },
          { id: "mm-hp-great-bay-4", name: "#4" },
          { id: "mm-hp-great-bay-5", name: "#5" },
          { id: "mm-hp-great-bay-6", name: "#6" },
          { id: "mm-hp-great-bay-7", name: "#7" },
          { id: "mm-hp-great-bay-8", name: "#8" },
          ],
        },
        {
          id: "mm-hp-ikana",
          name: "Cañón Ikana / Torre de Piedra",
          items: [
          { id: "mm-hp-ikana-1", name: "#1" },
          { id: "mm-hp-ikana-2", name: "#2" },
          { id: "mm-hp-ikana-3", name: "#3" },
          { id: "mm-hp-ikana-4", name: "#4" },
          { id: "mm-hp-ikana-5", name: "#5" },
          { id: "mm-hp-ikana-6", name: "#6" },
          { id: "mm-hp-ikana-7", name: "#7" },
          { id: "mm-hp-ikana-8", name: "#8" },
          ],
        },
        ],
      },
      {
        id: "mm-stray-fairies",
        name: "Hadas Perdidas",
        icon: "🧚",
        type: "grouped-list",
        note: "15 por cada una de las 4 mazmorras.",
        groups: [
        {
          id: "mm-sf-woodfall",
          name: "Templo del Pantano (Woodfall)",
          items: [
          { id: "mm-sf-woodfall-1", name: "#1" },
          { id: "mm-sf-woodfall-2", name: "#2" },
          { id: "mm-sf-woodfall-3", name: "#3" },
          { id: "mm-sf-woodfall-4", name: "#4" },
          { id: "mm-sf-woodfall-5", name: "#5" },
          { id: "mm-sf-woodfall-6", name: "#6" },
          { id: "mm-sf-woodfall-7", name: "#7" },
          { id: "mm-sf-woodfall-8", name: "#8" },
          { id: "mm-sf-woodfall-9", name: "#9" },
          { id: "mm-sf-woodfall-10", name: "#10" },
          { id: "mm-sf-woodfall-11", name: "#11" },
          { id: "mm-sf-woodfall-12", name: "#12" },
          { id: "mm-sf-woodfall-13", name: "#13" },
          { id: "mm-sf-woodfall-14", name: "#14" },
          { id: "mm-sf-woodfall-15", name: "#15" },
          ],
        },
        {
          id: "mm-sf-snowhead",
          name: "Templo de las Nieves (Snowhead)",
          items: [
          { id: "mm-sf-snowhead-1", name: "#1" },
          { id: "mm-sf-snowhead-2", name: "#2" },
          { id: "mm-sf-snowhead-3", name: "#3" },
          { id: "mm-sf-snowhead-4", name: "#4" },
          { id: "mm-sf-snowhead-5", name: "#5" },
          { id: "mm-sf-snowhead-6", name: "#6" },
          { id: "mm-sf-snowhead-7", name: "#7" },
          { id: "mm-sf-snowhead-8", name: "#8" },
          { id: "mm-sf-snowhead-9", name: "#9" },
          { id: "mm-sf-snowhead-10", name: "#10" },
          { id: "mm-sf-snowhead-11", name: "#11" },
          { id: "mm-sf-snowhead-12", name: "#12" },
          { id: "mm-sf-snowhead-13", name: "#13" },
          { id: "mm-sf-snowhead-14", name: "#14" },
          { id: "mm-sf-snowhead-15", name: "#15" },
          ],
        },
        {
          id: "mm-sf-great-bay",
          name: "Templo del Gran Mar (Great Bay)",
          items: [
          { id: "mm-sf-great-bay-1", name: "#1" },
          { id: "mm-sf-great-bay-2", name: "#2" },
          { id: "mm-sf-great-bay-3", name: "#3" },
          { id: "mm-sf-great-bay-4", name: "#4" },
          { id: "mm-sf-great-bay-5", name: "#5" },
          { id: "mm-sf-great-bay-6", name: "#6" },
          { id: "mm-sf-great-bay-7", name: "#7" },
          { id: "mm-sf-great-bay-8", name: "#8" },
          { id: "mm-sf-great-bay-9", name: "#9" },
          { id: "mm-sf-great-bay-10", name: "#10" },
          { id: "mm-sf-great-bay-11", name: "#11" },
          { id: "mm-sf-great-bay-12", name: "#12" },
          { id: "mm-sf-great-bay-13", name: "#13" },
          { id: "mm-sf-great-bay-14", name: "#14" },
          { id: "mm-sf-great-bay-15", name: "#15" },
          ],
        },
        {
          id: "mm-sf-stone-tower",
          name: "Templo de la Torre de Piedra (Stone Tower)",
          items: [
          { id: "mm-sf-stone-tower-1", name: "#1" },
          { id: "mm-sf-stone-tower-2", name: "#2" },
          { id: "mm-sf-stone-tower-3", name: "#3" },
          { id: "mm-sf-stone-tower-4", name: "#4" },
          { id: "mm-sf-stone-tower-5", name: "#5" },
          { id: "mm-sf-stone-tower-6", name: "#6" },
          { id: "mm-sf-stone-tower-7", name: "#7" },
          { id: "mm-sf-stone-tower-8", name: "#8" },
          { id: "mm-sf-stone-tower-9", name: "#9" },
          { id: "mm-sf-stone-tower-10", name: "#10" },
          { id: "mm-sf-stone-tower-11", name: "#11" },
          { id: "mm-sf-stone-tower-12", name: "#12" },
          { id: "mm-sf-stone-tower-13", name: "#13" },
          { id: "mm-sf-stone-tower-14", name: "#14" },
          { id: "mm-sf-stone-tower-15", name: "#15" },
          ],
        },
        ],
      },
    ],
  },
];
