/* Datos de checklists por juego.
 * Cada categoria puede ser de tipo:
 *   - "list": items nombrados sueltos.
 *   - "grid": coleccionables numerados sin ubicación (contador simple).
 *   - "grouped-list": coleccionables numerados pero agrupados por zona/mazmorra,
 *     para saber DONDE está cada uno (usado en Piezas de Corazón y Skulltulas).
 * Los IDs deben ser estables: si cambian, el progreso guardado de los usuarios se pierde.
 */
window.ZELDA_GAMES = [
  {
    id: "oot",
    name: "Ocarina of Time",
    subtitle: "The Legend of Zelda: Ocarina of Time (N64 / 3DS)",
    color: "#2d6a4f",
    categories: [
      {
        id: "stones",
        name: "Piedras Espirituales",
        icon: "💎",
        type: "list",
        items: [
          { id: "kokiri-emerald", name: "Esmeralda Kokiri" },
          { id: "goron-ruby", name: "Rubí Goron" },
          { id: "zora-sapphire", name: "Zafiro Zora" },
        ],
      },
      {
        id: "medallions",
        name: "Medallones de los Sabios",
        icon: "🔶",
        type: "list",
        items: [
          { id: "med-forest", name: "Medallón del Bosque" },
          { id: "med-fire", name: "Medallón del Fuego" },
          { id: "med-water", name: "Medallón del Agua" },
          { id: "med-shadow", name: "Medallón de las Sombras" },
          { id: "med-spirit", name: "Medallón del Espíritu" },
          { id: "med-light", name: "Medallón de la Luz" },
        ],
      },
      {
        id: "songs",
        name: "Canciones de Ocarina",
        icon: "🎵",
        type: "list",
        items: [
          { id: "song-zelda", name: "Canción de Zelda" },
          { id: "song-saria", name: "Canción de Saria" },
          { id: "song-epona", name: "Canción de Epona" },
          { id: "song-sun", name: "Canción del Sol" },
          { id: "song-time", name: "Canción del Tiempo" },
          { id: "song-storms", name: "Canción de la Tormenta" },
          { id: "song-minuet", name: "Minueto del Bosque" },
          { id: "song-bolero", name: "Bolero del Fuego" },
          { id: "song-serenade", name: "Serenata del Agua" },
          { id: "song-nocturne", name: "Nocturno de las Sombras" },
          { id: "song-requiem", name: "Réquiem del Espíritu" },
          { id: "song-prelude", name: "Preludio de la Luz" },
          { id: "song-scarecrow", name: "Canción del Espantapájaros" },
        ],
      },
      {
        id: "weapons",
        name: "Armas y Herramientas",
        icon: "⚔️",
        type: "list",
        items: [
          { id: "kokiri-sword", name: "Espada Kokiri" },
          { id: "master-sword", name: "Espada Maestra" },
          { id: "biggoron-sword", name: "Espada de Biggoron" },
          { id: "deku-shield", name: "Escudo Deku" },
          { id: "hylian-shield", name: "Escudo Hyliano" },
          { id: "mirror-shield", name: "Escudo Espejo" },
          { id: "deku-sticks", name: "Palos Deku" },
          { id: "deku-nuts", name: "Nueces Deku" },
          { id: "slingshot", name: "Tirachinas de las Hadas" },
          { id: "bombs", name: "Bombas / Bolsa de Bombas" },
          { id: "bombchus", name: "Bombchus" },
          { id: "fairy-bow", name: "Arco de las Hadas" },
          { id: "fire-arrows", name: "Flechas de Fuego" },
          { id: "ice-arrows", name: "Flechas de Hielo" },
          { id: "light-arrows", name: "Flechas de Luz" },
          { id: "boomerang", name: "Bumerán" },
          { id: "hookshot", name: "Gancho" },
          { id: "longshot", name: "Gancho Largo" },
          { id: "megaton-hammer", name: "Martillo Megatón" },
          { id: "lens-of-truth", name: "Lupa de la Verdad" },
          { id: "iron-boots", name: "Botas de Hierro" },
          { id: "hover-boots", name: "Botas Saltarinas" },
          { id: "ocarina", name: "Ocarina (de las Hadas / del Tiempo)" },
        ],
      },
      {
        id: "magic",
        name: "Magia y Trajes",
        icon: "✨",
        type: "list",
        items: [
          { id: "dins-fire", name: "Fuego de Din" },
          { id: "farores-wind", name: "Viento de Farore" },
          { id: "nayrus-love", name: "Amor de Nayru" },
          { id: "goron-tunic", name: "Traje Goron" },
          { id: "zora-tunic", name: "Traje Zora" },
        ],
      },
      {
        id: "bottles",
        name: "Botellas",
        icon: "🍾",
        type: "list",
        items: [
          { id: "bottle-1", name: "Botella #1" },
          { id: "bottle-2", name: "Botella #2" },
          { id: "bottle-3", name: "Botella #3" },
          { id: "bottle-4", name: "Botella #4 (Gran Hada de Poe)" },
        ],
      },
      {
        id: "masks",
        name: "Máscaras",
        icon: "🎭",
        type: "list",
        items: [
          { id: "mask-keaton", name: "Máscara de Keaton" },
          { id: "mask-skull", name: "Máscara Calavera" },
          { id: "mask-spooky", name: "Máscara Espeluznante" },
          { id: "mask-bunny", name: "Careta de Conejo" },
          { id: "mask-goron", name: "Máscara Goron" },
          { id: "mask-zora", name: "Máscara Zora" },
          { id: "mask-gerudo", name: "Máscara Gerudo" },
          { id: "mask-truth", name: "Máscara de la Verdad" },
        ],
      },
      {
        id: "trading",
        name: "Secuencia de Intercambio (Adulto)",
        icon: "🔄",
        type: "list",
        items: [
          { id: "trade-pocket-egg", name: "Huevo de Bolsillo" },
          { id: "trade-pocket-cucco", name: "Cucco de Bolsillo" },
          { id: "trade-cojiro", name: "Cojiro" },
          { id: "trade-odd-mushroom", name: "Seta Extraña" },
          { id: "trade-odd-potion", name: "Poción Extraña" },
          { id: "trade-saw", name: "Sierra del Cazador" },
          { id: "trade-broken-sword", name: "Espada Rota del Gigante" },
          { id: "trade-prescription", name: "Receta" },
          { id: "trade-frog", name: "Rana de Ojo" },
          { id: "trade-eyedrops", name: "Colirio del Mundo" },
          { id: "trade-claim-check", name: "Recibo (Claim Check)" },
        ],
      },
      {
        id: "upgrades",
        name: "Mejoras y Equipamiento",
        icon: "📈",
        type: "list",
        items: [
          { id: "up-bombbag-20", name: "Bolsa de Bombas (20)" },
          { id: "up-bombbag-30", name: "Bolsa de Bombas (30)" },
          { id: "up-bombbag-40", name: "Bolsa de Bombas (40)" },
          { id: "up-quiver-30", name: "Carcaj (30 flechas)" },
          { id: "up-quiver-40", name: "Carcaj (40 flechas)" },
          { id: "up-quiver-50", name: "Carcaj (50 flechas)" },
          { id: "up-stick-20", name: "Bolsillo Palos Deku (20)" },
          { id: "up-stick-30", name: "Bolsillo Palos Deku (30)" },
          { id: "up-nut-30", name: "Bolsillo Nueces Deku (30)" },
          { id: "up-nut-40", name: "Bolsillo Nueces Deku (40)" },
          { id: "up-wallet-adult", name: "Billetera de Adulto (200)" },
          { id: "up-wallet-giant", name: "Billetera Gigante (500)" },
          { id: "up-scale-silver", name: "Escama de Plata" },
          { id: "up-scale-gold", name: "Escama Dorada" },
          { id: "up-gauntlets-silver", name: "Guantes de Plata" },
          { id: "up-gauntlets-gold", name: "Guantes Dorados" },
          { id: "up-stone-agony", name: "Piedra de la Agonía" },
          { id: "up-magic", name: "Ampliación de Magia" },
          { id: "up-magic-double", name: "Doble Magia" },
        ],
      },
      {
        id: "bosses",
        name: "Jefes y Contenedores de Corazón",
        icon: "❤️",
        type: "list",
        items: [
          { id: "boss-gohma", name: "Gohma (Gran Árbol Deku)" },
          { id: "boss-dodongo", name: "Rey Dodongo (Caverna Dodongo)" },
          { id: "boss-barinade", name: "Barinade (Vientre de Jabu-Jabu)" },
          { id: "boss-phantom-ganon", name: "Phantom Ganon (Templo del Bosque)" },
          { id: "boss-volvagia", name: "Volvagia (Templo del Fuego)" },
          { id: "boss-morpha", name: "Morpha (Templo del Agua)" },
          { id: "boss-bongo-bongo", name: "Bongo Bongo (Templo de las Sombras)" },
          { id: "boss-twinrova", name: "Twinrova (Templo del Espíritu)" },
          { id: "boss-ganon", name: "Ganon (batalla final)" },
        ],
      },
      {
        id: "dungeons",
        name: "Mazmorras Completadas",
        icon: "🏰",
        type: "list",
        items: [
          { id: "dun-deku-tree", name: "Gran Árbol Deku" },
          { id: "dun-dodongo", name: "Caverna Dodongo" },
          { id: "dun-jabu", name: "Vientre de Jabu-Jabu" },
          { id: "dun-forest", name: "Templo del Bosque" },
          { id: "dun-fire", name: "Templo del Fuego" },
          { id: "dun-water", name: "Templo del Agua" },
          { id: "dun-well", name: "Pozo del Fondo (Bottom of the Well)" },
          { id: "dun-shadow", name: "Templo de las Sombras" },
          { id: "dun-spirit", name: "Templo del Espíritu" },
          { id: "dun-ice", name: "Caverna de Hielo" },
          { id: "dun-gtg", name: "Terreno de Entrenamiento Gerudo" },
          { id: "dun-ganons-castle", name: "Castillo de Ganon" },
        ],
      },
      {
        id: "heart-pieces",
        name: "Piezas de Corazón",
        icon: "💗",
        type: "grouped-list",
        note: "36 piezas = 9 contenedores extra de corazón.",
        groups: [
        {
          id: "hp-graveyard",
          name: "Cementerio de Kakariko",
          items: [
          { id: "hp-1", name: "#1" },
          { id: "hp-2", name: "#2" },
          { id: "hp-19", name: "#19" },
          ],
        },
        {
          id: "hp-lon-lon",
          name: "Rancho Lon Lon",
          items: [
          { id: "hp-3", name: "#3" },
          ],
        },
        {
          id: "hp-gerudo-valley",
          name: "Valle Gerudo",
          items: [
          { id: "hp-4", name: "#4" },
          { id: "hp-6", name: "#6" },
          ],
        },
        {
          id: "hp-fishing-pond",
          name: "Estanque de Pesca",
          items: [
          { id: "hp-5", name: "#5" },
          ],
        },
        {
          id: "hp-lost-woods",
          name: "Bosque Perdido",
          items: [
          { id: "hp-7", name: "#7" },
          { id: "hp-8", name: "#8" },
          ],
        },
        {
          id: "hp-market",
          name: "Ciudadela de Hyrule",
          items: [
          { id: "hp-9", name: "#9" },
          ],
        },
        {
          id: "hp-goron-city",
          name: "Ciudad Goron",
          items: [
          { id: "hp-10", name: "#10" },
          ],
        },
        {
          id: "hp-death-mountain",
          name: "Montaña de la Muerte",
          items: [
          { id: "hp-11", name: "#11" },
          ],
        },
        {
          id: "hp-dmc",
          name: "Cráter de la Montaña de la Muerte",
          items: [
          { id: "hp-12", name: "#12" },
          { id: "hp-27", name: "#27" },
          ],
        },
        {
          id: "hp-kakariko",
          name: "Kakariko",
          items: [
          { id: "hp-13", name: "#13" },
          { id: "hp-22", name: "#22" },
          ],
        },
        {
          id: "hp-bombchu-bowling",
          name: "Bolera Bombuchu",
          items: [
          { id: "hp-14", name: "#14" },
          ],
        },
        {
          id: "hp-hyrule-field",
          name: "Pradera de Hyrule",
          items: [
          { id: "hp-15", name: "#15" },
          { id: "hp-26", name: "#26" },
          ],
        },
        {
          id: "hp-zora-river",
          name: "Río Zora",
          items: [
          { id: "hp-16", name: "#16" },
          { id: "hp-17", name: "#17" },
          { id: "hp-31", name: "#31" },
          { id: "hp-32", name: "#32" },
          ],
        },
        {
          id: "hp-zora-domain",
          name: "Dominio Zora",
          items: [
          { id: "hp-18", name: "#18" },
          ],
        },
        {
          id: "hp-windmill",
          name: "Molino",
          items: [
          { id: "hp-20", name: "#20" },
          ],
        },
        {
          id: "hp-dampe-grave",
          name: "Tumba de Dampé",
          items: [
          { id: "hp-21", name: "#21" },
          ],
        },
        {
          id: "hp-skulltula-house",
          name: "Casa de las Skulltulas",
          items: [
          { id: "hp-23", name: "#23" },
          ],
        },
        {
          id: "hp-lake-hylia",
          name: "Lago Hylia",
          items: [
          { id: "hp-24", name: "#24" },
          ],
        },
        {
          id: "hp-lake-lab",
          name: "Laboratorio del Lago",
          items: [
          { id: "hp-25", name: "#25" },
          ],
        },
        {
          id: "hp-zora-fountain",
          name: "Fuente Zora",
          items: [
          { id: "hp-28", name: "#28" },
          { id: "hp-30", name: "#30" },
          ],
        },
        {
          id: "hp-ice-cavern",
          name: "Caverna de Hielo",
          items: [
          { id: "hp-29", name: "#29" },
          ],
        },
        {
          id: "hp-treasure-chest-game",
          name: "Concurso de Cofres del Tesoro",
          items: [
          { id: "hp-33", name: "#33" },
          ],
        },
        {
          id: "hp-gerudo-fortress",
          name: "Fortaleza Gerudo",
          items: [
          { id: "hp-34", name: "#34" },
          { id: "hp-35", name: "#35" },
          ],
        },
        {
          id: "hp-desert-colossus",
          name: "Coloso del Desierto",
          items: [
          { id: "hp-36", name: "#36" },
          ],
        },
        ],
      },
      {
        id: "skulltulas-dungeons",
        name: "Skulltulas Doradas — Mazmorras",
        icon: "🕷️",
        type: "grouped-list",
        note: "44 en las 10 mazmorras con Skulltulas (no reparten 5 por igual).",
        groups: [
        {
          id: "sk-deku-tree",
          name: "Gran Árbol Deku",
          items: [
          { id: "sk-1", name: "#1" },
          { id: "sk-2", name: "#2" },
          { id: "sk-3", name: "#3" },
          { id: "sk-36", name: "#36" },
          ],
        },
        {
          id: "sk-dodongo",
          name: "Caverna Dodongo",
          items: [
          { id: "sk-22", name: "#22" },
          { id: "sk-23", name: "#23" },
          { id: "sk-24", name: "#24" },
          { id: "sk-44", name: "#44" },
          { id: "sk-55", name: "#55" },
          ],
        },
        {
          id: "sk-jabu",
          name: "Vientre de Jabu-Jabu",
          items: [
          { id: "sk-31", name: "#31" },
          { id: "sk-32", name: "#32" },
          { id: "sk-33", name: "#33" },
          { id: "sk-34", name: "#34" },
          ],
        },
        {
          id: "sk-bottom-well",
          name: "Pozo del Fondo",
          items: [
          { id: "sk-79", name: "#79" },
          { id: "sk-80", name: "#80" },
          { id: "sk-81", name: "#81" },
          ],
        },
        {
          id: "sk-spirit-temple",
          name: "Templo del Espíritu",
          items: [
          { id: "sk-93", name: "#93" },
          { id: "sk-94", name: "#94" },
          { id: "sk-95", name: "#95" },
          { id: "sk-98", name: "#98" },
          { id: "sk-99", name: "#99" },
          ],
        },
        {
          id: "sk-forest-temple",
          name: "Templo del Bosque",
          items: [
          { id: "sk-50", name: "#50" },
          { id: "sk-51", name: "#51" },
          { id: "sk-52", name: "#52" },
          { id: "sk-53", name: "#53" },
          { id: "sk-54", name: "#54" },
          ],
        },
        {
          id: "sk-fire-temple",
          name: "Templo del Fuego",
          items: [
          { id: "sk-58", name: "#58" },
          { id: "sk-59", name: "#59" },
          { id: "sk-60", name: "#60" },
          { id: "sk-61", name: "#61" },
          { id: "sk-62", name: "#62" },
          ],
        },
        {
          id: "sk-ice-cavern",
          name: "Caverna de Hielo",
          items: [
          { id: "sk-68", name: "#68" },
          { id: "sk-69", name: "#69" },
          { id: "sk-70", name: "#70" },
          ],
        },
        {
          id: "sk-water-temple",
          name: "Templo del Agua",
          items: [
          { id: "sk-72", name: "#72" },
          { id: "sk-73", name: "#73" },
          { id: "sk-74", name: "#74" },
          { id: "sk-75", name: "#75" },
          { id: "sk-76", name: "#76" },
          ],
        },
        {
          id: "sk-shadow-temple",
          name: "Templo de las Sombras",
          items: [
          { id: "sk-82", name: "#82" },
          { id: "sk-83", name: "#83" },
          { id: "sk-84", name: "#84" },
          { id: "sk-85", name: "#85" },
          { id: "sk-86", name: "#86" },
          ],
        },
        ],
      },
      {
        id: "skulltulas-overworld",
        name: "Skulltulas Doradas — Mundo",
        icon: "🕸️",
        type: "grouped-list",
        note: "Repartidas por Hyrule. Muchas solo aparecen de noche.",
        groups: [
        {
          id: "sk-market",
          name: "Ciudadela de Hyrule",
          items: [
          { id: "sk-4", name: "#4" },
          ],
        },
        {
          id: "sk-castle-grounds",
          name: "Terrenos del Castillo",
          items: [
          { id: "sk-5", name: "#5" },
          { id: "sk-78", name: "#78" },
          ],
        },
        {
          id: "sk-kakariko",
          name: "Kakariko",
          items: [
          { id: "sk-6", name: "#6" },
          { id: "sk-7", name: "#7" },
          { id: "sk-8", name: "#8" },
          { id: "sk-9", name: "#9" },
          { id: "sk-10", name: "#10" },
          { id: "sk-45", name: "#45" },
          ],
        },
        {
          id: "sk-graveyard",
          name: "Cementerio de Kakariko",
          items: [
          { id: "sk-11", name: "#11" },
          { id: "sk-43", name: "#43" },
          ],
        },
        {
          id: "sk-lon-lon",
          name: "Rancho Lon Lon",
          items: [
          { id: "sk-12", name: "#12" },
          { id: "sk-13", name: "#13" },
          { id: "sk-40", name: "#40" },
          { id: "sk-41", name: "#41" },
          ],
        },
        {
          id: "sk-lake-hylia",
          name: "Lago Hylia",
          items: [
          { id: "sk-14", name: "#14" },
          { id: "sk-15", name: "#15" },
          { id: "sk-37", name: "#37" },
          { id: "sk-77", name: "#77" },
          ],
        },
        {
          id: "sk-gerudo-valley",
          name: "Valle Gerudo",
          items: [
          { id: "sk-16", name: "#16" },
          { id: "sk-39", name: "#39" },
          { id: "sk-87", name: "#87" },
          { id: "sk-88", name: "#88" },
          ],
        },
        {
          id: "sk-kokiri-forest",
          name: "Bosque Kokiri",
          items: [
          { id: "sk-17", name: "#17" },
          { id: "sk-18", name: "#18" },
          { id: "sk-47", name: "#47" },
          ],
        },
        {
          id: "sk-lost-woods",
          name: "Bosque Perdido",
          items: [
          { id: "sk-19", name: "#19" },
          { id: "sk-20", name: "#20" },
          { id: "sk-48", name: "#48" },
          ],
        },
        {
          id: "sk-death-mountain",
          name: "Montaña de la Muerte",
          items: [
          { id: "sk-21", name: "#21" },
          { id: "sk-25", name: "#25" },
          { id: "sk-63", name: "#63" },
          { id: "sk-64", name: "#64" },
          ],
        },
        {
          id: "sk-goron-city",
          name: "Ciudad Goron",
          items: [
          { id: "sk-26", name: "#26" },
          { id: "sk-56", name: "#56" },
          ],
        },
        {
          id: "sk-dmc",
          name: "Cráter de la Montaña de la Muerte",
          items: [
          { id: "sk-27", name: "#27" },
          { id: "sk-57", name: "#57" },
          ],
        },
        {
          id: "sk-zora-river",
          name: "Río Zora",
          items: [
          { id: "sk-28", name: "#28" },
          { id: "sk-29", name: "#29" },
          { id: "sk-65", name: "#65" },
          { id: "sk-66", name: "#66" },
          ],
        },
        {
          id: "sk-zora-fountain",
          name: "Fuente Zora",
          items: [
          { id: "sk-30", name: "#30" },
          { id: "sk-35", name: "#35" },
          { id: "sk-100", name: "#100" },
          ],
        },
        {
          id: "sk-hyrule-field",
          name: "Pradera de Hyrule",
          items: [
          { id: "sk-38", name: "#38" },
          { id: "sk-42", name: "#42" },
          ],
        },
        {
          id: "sk-ganons-tower",
          name: "Torre de Ganon",
          items: [
          { id: "sk-46", name: "#46" },
          ],
        },
        {
          id: "sk-sacred-meadow",
          name: "Pradera Sagrada del Bosque",
          items: [
          { id: "sk-49", name: "#49" },
          ],
        },
        {
          id: "sk-zora-domain",
          name: "Dominio Zora",
          items: [
          { id: "sk-67", name: "#67" },
          ],
        },
        {
          id: "sk-lake-lab",
          name: "Laboratorio del Lago",
          items: [
          { id: "sk-71", name: "#71" },
          ],
        },
        {
          id: "sk-gerudo-fortress",
          name: "Fortaleza Gerudo",
          items: [
          { id: "sk-89", name: "#89" },
          { id: "sk-90", name: "#90" },
          ],
        },
        {
          id: "sk-wasteland",
          name: "Búnker del Desierto",
          items: [
          { id: "sk-91", name: "#91" },
          ],
        },
        {
          id: "sk-desert-colossus",
          name: "Coloso del Desierto",
          items: [
          { id: "sk-92", name: "#92" },
          { id: "sk-96", name: "#96" },
          { id: "sk-97", name: "#97" },
          ],
        },
        ],
      },
    ],
  },
  {
    id: "mm",
    name: "Majora's Mask",
    subtitle: "The Legend of Zelda: Majora's Mask (N64 / 3DS)",
    color: "#5a3d8a",
    categories: [
      {
        id: "mm-transformation-masks",
        name: "Máscaras de Transformación",
        icon: "🎭",
        type: "list",
        items: [
          { id: "mm-mask-deku", name: "Máscara Deku" },
          { id: "mm-mask-goron", name: "Máscara Goron" },
          { id: "mm-mask-zora", name: "Máscara Zora" },
          { id: "mm-mask-fierce-deity", name: "Máscara de la Deidad Feroz" },
        ],
      },
      {
        id: "mm-masks",
        name: "Otras Máscaras",
        icon: "🎪",
        type: "list",
        items: [
          { id: "mm-mask-moon", name: "Máscara de la Luna" },
          { id: "mm-mask-all-night", name: "Máscara del Trasnoche" },
          { id: "mm-mask-bunny-hood", name: "Careta de Conejo" },
          { id: "mm-mask-keaton", name: "Máscara de Keaton" },
          { id: "mm-mask-garo", name: "Máscara Garo" },
          { id: "mm-mask-romani", name: "Máscara de Romani" },
          { id: "mm-mask-circus-leader", name: "Máscara del Líder del Circo" },
          { id: "mm-mask-postman", name: "Gorro de Cartero" },
          { id: "mm-mask-couple", name: "Máscara de los Novios" },
          { id: "mm-mask-great-fairy", name: "Máscara de la Gran Hada" },
          { id: "mm-mask-gibdo", name: "Máscara Gibdo" },
          { id: "mm-mask-don-gero", name: "Máscara de Don Gero" },
          { id: "mm-mask-kamaro", name: "Máscara de Kamaro" },
          { id: "mm-mask-captains-hat", name: "Casco del Capitán" },
          { id: "mm-mask-giants", name: "Máscara de los Gigantes" },
          { id: "mm-mask-blast", name: "Máscara Explosiva" },
          { id: "mm-mask-stone", name: "Máscara de Piedra" },
          { id: "mm-mask-scents", name: "Máscara de Aromas" },
          { id: "mm-mask-truth", name: "Máscara de la Verdad" },
        ],
      },
      {
        id: "mm-songs",
        name: "Canciones",
        icon: "🎵",
        type: "list",
        items: [
          { id: "mm-song-oath", name: "Canción del Juramento" },
          { id: "mm-song-healing", name: "Canción de Curación" },
          { id: "mm-song-time", name: "Canción del Tiempo" },
          { id: "mm-song-sonata", name: "Sonata de la Tempestad" },
          { id: "mm-song-lullaby", name: "Canción de Cuna de la Nueva Onda" },
          { id: "mm-song-elegy", name: "Elegía de la Emptiness" },
          { id: "mm-song-oath-goron", name: "Canción del Juramento a un Amigo (obtención)" },
          { id: "mm-song-sarias", name: "Canción de Saria" },
          { id: "mm-song-suns", name: "Canción del Sol" },
          { id: "mm-song-storms", name: "Canción de la Tormenta" },
          { id: "mm-song-epona", name: "Canción de Epona" },
          { id: "mm-song-goron-lullaby", name: "Canción de Cuna Goron" },
        ],
      },
      {
        id: "mm-dungeons",
        name: "Mazmorras y Gigantes",
        icon: "🏰",
        type: "list",
        items: [
          { id: "mm-woodfall", name: "Templo del Pantano (Woodfall)" },
          { id: "mm-snowhead", name: "Templo de las Nieves (Snowhead)" },
          { id: "mm-great-bay", name: "Templo del Gran Mar (Great Bay)" },
          { id: "mm-stone-tower", name: "Templo de la Torre de Piedra (Stone Tower)" },
        ],
      },
      {
        id: "mm-heart-pieces",
        name: "Piezas de Corazón",
        icon: "💗",
        type: "grouped-list",
        note: "44 piezas = 11 contenedores extra de corazón.",
        groups: [
        {
          id: "mm-hp-clock-town",
          name: "Ciudad Reloj",
          items: [
          { id: "mm-hp-clock-town-1", name: "#1" },
          { id: "mm-hp-clock-town-2", name: "#2" },
          { id: "mm-hp-clock-town-3", name: "#3" },
          { id: "mm-hp-clock-town-4", name: "#4" },
          { id: "mm-hp-clock-town-5", name: "#5" },
          { id: "mm-hp-clock-town-6", name: "#6" },
          { id: "mm-hp-clock-town-7", name: "#7" },
          { id: "mm-hp-clock-town-8", name: "#8" },
          ],
        },
        {
          id: "mm-hp-termina-field",
          name: "Campo Termina",
          items: [
          { id: "mm-hp-termina-field-1", name: "#1" },
          { id: "mm-hp-termina-field-2", name: "#2" },
          { id: "mm-hp-termina-field-3", name: "#3" },
          { id: "mm-hp-termina-field-4", name: "#4" },
          { id: "mm-hp-termina-field-5", name: "#5" },
          { id: "mm-hp-termina-field-6", name: "#6" },
          ],
        },
        {
          id: "mm-hp-woodfall",
          name: "Pantano (Woodfall)",
          items: [
          { id: "mm-hp-woodfall-1", name: "#1" },
          { id: "mm-hp-woodfall-2", name: "#2" },
          { id: "mm-hp-woodfall-3", name: "#3" },
          { id: "mm-hp-woodfall-4", name: "#4" },
          { id: "mm-hp-woodfall-5", name: "#5" },
          { id: "mm-hp-woodfall-6", name: "#6" },
          ],
        },
        {
          id: "mm-hp-snowhead",
          name: "Montaña (Snowhead)",
          items: [
          { id: "mm-hp-snowhead-1", name: "#1" },
          { id: "mm-hp-snowhead-2", name: "#2" },
          { id: "mm-hp-snowhead-3", name: "#3" },
          { id: "mm-hp-snowhead-4", name: "#4" },
          { id: "mm-hp-snowhead-5", name: "#5" },
          { id: "mm-hp-snowhead-6", name: "#6" },
          { id: "mm-hp-snowhead-7", name: "#7" },
          { id: "mm-hp-snowhead-8", name: "#8" },
          ],
        },
        {
          id: "mm-hp-great-bay",
          name: "Bahía / Costa Zora (Great Bay)",
          items: [
          { id: "mm-hp-great-bay-1", name: "#1" },
          { id: "mm-hp-great-bay-2", name: "#2" },
          { id: "mm-hp-great-bay-3", name: "#3" },
          { id: "mm-hp-great-bay-4", name: "#4" },
          { id: "mm-hp-great-bay-5", name: "#5" },
          { id: "mm-hp-great-bay-6", name: "#6" },
          { id: "mm-hp-great-bay-7", name: "#7" },
          { id: "mm-hp-great-bay-8", name: "#8" },
          ],
        },
        {
          id: "mm-hp-ikana",
          name: "Cañón Ikana / Torre de Piedra",
          items: [
          { id: "mm-hp-ikana-1", name: "#1" },
          { id: "mm-hp-ikana-2", name: "#2" },
          { id: "mm-hp-ikana-3", name: "#3" },
          { id: "mm-hp-ikana-4", name: "#4" },
          { id: "mm-hp-ikana-5", name: "#5" },
          { id: "mm-hp-ikana-6", name: "#6" },
          { id: "mm-hp-ikana-7", name: "#7" },
          { id: "mm-hp-ikana-8", name: "#8" },
          ],
        },
        ],
      },
      {
        id: "mm-stray-fairies",
        name: "Hadas Perdidas",
        icon: "🧚",
        type: "grouped-list",
        note: "15 por cada una de las 4 mazmorras.",
        groups: [
        {
          id: "mm-sf-woodfall",
          name: "Templo del Pantano (Woodfall)",
          items: [
          { id: "mm-sf-woodfall-1", name: "#1" },
          { id: "mm-sf-woodfall-2", name: "#2" },
          { id: "mm-sf-woodfall-3", name: "#3" },
          { id: "mm-sf-woodfall-4", name: "#4" },
          { id: "mm-sf-woodfall-5", name: "#5" },
          { id: "mm-sf-woodfall-6", name: "#6" },
          { id: "mm-sf-woodfall-7", name: "#7" },
          { id: "mm-sf-woodfall-8", name: "#8" },
          { id: "mm-sf-woodfall-9", name: "#9" },
          { id: "mm-sf-woodfall-10", name: "#10" },
          { id: "mm-sf-woodfall-11", name: "#11" },
          { id: "mm-sf-woodfall-12", name: "#12" },
          { id: "mm-sf-woodfall-13", name: "#13" },
          { id: "mm-sf-woodfall-14", name: "#14" },
          { id: "mm-sf-woodfall-15", name: "#15" },
          ],
        },
        {
          id: "mm-sf-snowhead",
          name: "Templo de las Nieves (Snowhead)",
          items: [
          { id: "mm-sf-snowhead-1", name: "#1" },
          { id: "mm-sf-snowhead-2", name: "#2" },
          { id: "mm-sf-snowhead-3", name: "#3" },
          { id: "mm-sf-snowhead-4", name: "#4" },
          { id: "mm-sf-snowhead-5", name: "#5" },
          { id: "mm-sf-snowhead-6", name: "#6" },
          { id: "mm-sf-snowhead-7", name: "#7" },
          { id: "mm-sf-snowhead-8", name: "#8" },
          { id: "mm-sf-snowhead-9", name: "#9" },
          { id: "mm-sf-snowhead-10", name: "#10" },
          { id: "mm-sf-snowhead-11", name: "#11" },
          { id: "mm-sf-snowhead-12", name: "#12" },
          { id: "mm-sf-snowhead-13", name: "#13" },
          { id: "mm-sf-snowhead-14", name: "#14" },
          { id: "mm-sf-snowhead-15", name: "#15" },
          ],
        },
        {
          id: "mm-sf-great-bay",
          name: "Templo del Gran Mar (Great Bay)",
          items: [
          { id: "mm-sf-great-bay-1", name: "#1" },
          { id: "mm-sf-great-bay-2", name: "#2" },
          { id: "mm-sf-great-bay-3", name: "#3" },
          { id: "mm-sf-great-bay-4", name: "#4" },
          { id: "mm-sf-great-bay-5", name: "#5" },
          { id: "mm-sf-great-bay-6", name: "#6" },
          { id: "mm-sf-great-bay-7", name: "#7" },
          { id: "mm-sf-great-bay-8", name: "#8" },
          { id: "mm-sf-great-bay-9", name: "#9" },
          { id: "mm-sf-great-bay-10", name: "#10" },
          { id: "mm-sf-great-bay-11", name: "#11" },
          { id: "mm-sf-great-bay-12", name: "#12" },
          { id: "mm-sf-great-bay-13", name: "#13" },
          { id: "mm-sf-great-bay-14", name: "#14" },
          { id: "mm-sf-great-bay-15", name: "#15" },
          ],
        },
        {
          id: "mm-sf-stone-tower",
          name: "Templo de la Torre de Piedra (Stone Tower)",
          items: [
          { id: "mm-sf-stone-tower-1", name: "#1" },
          { id: "mm-sf-stone-tower-2", name: "#2" },
          { id: "mm-sf-stone-tower-3", name: "#3" },
          { id: "mm-sf-stone-tower-4", name: "#4" },
          { id: "mm-sf-stone-tower-5", name: "#5" },
          { id: "mm-sf-stone-tower-6", name: "#6" },
          { id: "mm-sf-stone-tower-7", name: "#7" },
          { id: "mm-sf-stone-tower-8", name: "#8" },
          { id: "mm-sf-stone-tower-9", name: "#9" },
          { id: "mm-sf-stone-tower-10", name: "#10" },
          { id: "mm-sf-stone-tower-11", name: "#11" },
          { id: "mm-sf-stone-tower-12", name: "#12" },
          { id: "mm-sf-stone-tower-13", name: "#13" },
          { id: "mm-sf-stone-tower-14", name: "#14" },
          { id: "mm-sf-stone-tower-15", name: "#15" },
          ],
        },
        ],
      },
    ],
  },
];
